version: "3.7"

services:
  bachelor:
    # image: deep-learning
    build: .
    ports:
      - 9999:9999
      - 6006:6006
    working_dir: /all
    volumes:
      - .:/all
    stdin_open: true # docker run -i
    tty: true # docker run -t
    # command: bash
