version: "3.7"

services:
  replicability:
    environment:
        - JUPYTER_CONFIG_DIR="/all/.jupyter"
    build:
      dockerfile: ./Dockerfile
      context: ./
    image: replicability
    ports:
      - 9009:9009
    working_dir: /all
    command: bash -c "JUPYTER_CONFIG_DIR=/all/.jupyter jupyter lab --no-browser --ip=0.0.0.0 --port=9009 --allow-root --ServerApp.token='7cf55c2887d81e8ea8da627112d0753e4b4fc79345f121fc'"
    volumes:
      - .:/all
    environment:
      - SHELL=/bin/bash # Default Shell, important for jupyter shell too
      - JUPYTER_ENABLE_LAB=yes
    stdin_open: true # docker run -i
    tty: true # docker run -t
